- name: Añadir clave GPG de Grafana
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Añadir repositorio de Grafana
  apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present

- name: Actualizar repositorios
  apt:
    update_cache: yes

- name: Instalar Grafana
  apt:
    name: grafana
    state: present



- name: Configurar Grafana para usar TLS
  lineinfile:
    path: "/etc/grafana/grafana.ini"
    regexp: '^;http_addr ='
    line: 'http_addr = 0.0.0.0'

- name: Habilitar TLS en Grafana
  lineinfile:
    path: "/etc/grafana/grafana.ini"
    regexp: '^;protocol ='
    line: 'protocol = https'

- name: Habilitar TLS en Grafana
  lineinfile:
    path: "/etc/grafana/grafana.ini"
    regexp: '^;cert_file ='
    line: 'cert_file = /etc/ssl/certs/monitoring/monitoring.crt'

- name: Habilitar TLS en Grafana
  lineinfile:
    path: "/etc/grafana/grafana.ini"
    regexp: '^;cert_key ='
    line: 'cert_key = /etc/ssl/certs/monitoring/monitoring.key'



- name: Habilitar y reiniciar Grafana
  service:
    name: grafana-server
    enabled: yes
    state: restarted


- name: Esperar a que Grafana inicie
  wait_for:
    port: 3000
    delay: 10
    timeout: 30

- name: Configurar Prometheus como fuente de datos en Grafana
  uri:
    url: "https://localhost:3000/api/datasources"
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    body: |
      {
        "name": "Prometheus",
        "type": "prometheus",
        "url": "https://localhost:9090",
        "access": "proxy",
        "isDefault": true,
        "jsonData": {
          "httpMethod": "POST",
          "insecureSkipVerify": true
        },
        "secureJsonData": {
          "tlsClientCert": "/etc/ssl/certs/monitoring/monitoring.crt",
          "tlsClientKey": "/etc/ssl/certs/monitoring/monitoring.key"
        }
      }
    status_code: [200, 409]
    validate_certs: no  # Disable SSL certificate validation for self-signed certificates

- name: Subir dashboard predefinido a Grafana
  uri:
    url: "https://localhost:3000/api/dashboards/db"
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{{ lookup('file', 'roles/grafana/files/dashboard.json') }}"
    status_code: [200, 409]
    validate_certs: no  # Disable SSL certificate validation for self-signed certificates