- name: Add GPG Grafana key
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present

- name: Update apt repositories
  apt:
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Configure Grafana to listen
  lineinfile:
    path: "/etc/grafana/grafana.ini"
    regexp: '^;http_addr ='
    line: 'http_addr = 0.0.0.0'

- name: Enable TLS in Grafana
  lineinfile:
    path: "/etc/grafana/grafana.ini"
    regexp: '^;protocol ='
    line: 'protocol = https'

- name: Add monitoring certificate
  lineinfile:
    path: "/etc/grafana/grafana.ini"
    regexp: '^;cert_file ='
    line: 'cert_file = /etc/ssl/certs/monitoring/monitoring.crt'

- name: Add certificate key
  lineinfile:
    path: "/etc/grafana/grafana.ini"
    regexp: '^;cert_key ='
    line: 'cert_key = /etc/ssl/certs/monitoring/monitoring.key'

- name: Restart Grafana
  service:
    name: grafana-server
    enabled: yes
    state: restarted

- name: Wait for Grafana to load
  wait_for:
    port: 3000
    delay: 10
    timeout: 30

- name: Configure Prometheus as a data source in Grafana
  uri:
    url: "https://localhost:3000/api/datasources"
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    body: |
      {
        "name": "Prometheus",
        "type": "prometheus",
        "url": "https://localhost:9090",
        "access": "proxy",
        "isDefault": true,
        "jsonData": {
          "httpMethod": "POST",
          "insecureSkipVerify": true
        },
        "secureJsonData": {
          "tlsClientCert": "/etc/ssl/certs/monitoring/monitoring.crt",
          "tlsClientKey": "/etc/ssl/certs/monitoring/monitoring.key"
        }
      }
    status_code: [200, 409]
    validate_certs: no  # Disable SSL certificate validation for self-signed certificates

- name: Upload a Node Exporter metrics dashboard to Grafana
  uri:
    url: "https://localhost:3000/api/dashboards/db"
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{{ lookup('file', 'roles/grafana/files/dashboard.json') }}"
    status_code: [200, 409]
    validate_certs: no  # Disable SSL certificate validation for self-signed certificates