- name: Create directory for certificates
  file:
    path: "/etc/ssl/certs/monitoring"
    state: directory
    mode: '0755'

- name: Generate private key for the monitoring server
  openssl_privatekey:
    path: "/etc/ssl/certs/monitoring/monitoring.key"
    size: 2048
    state: present

- name: Generate csr for Prometheus and Grafana
  openssl_csr:
    path: "/etc/ssl/certs/monitoring/monitoring.csr"
    privatekey_path: "/etc/ssl/certs/monitoring/monitoring.key"
    common_name: "monitoring.local"
    state: present

- name: Generate self-signed certificate for the monitoring server
  openssl_certificate:
    path: "/etc/ssl/certs/monitoring/monitoring.crt"
    csr_path: "/etc/ssl/certs/monitoring/monitoring.csr"
    privatekey_path: "/etc/ssl/certs/monitoring/monitoring.key"
    provider: selfsigned
    state: present
