---
- name: Configurar Servidores de Monitorización
  hosts: monitoring_server
  become: yes
  roles:
    - tls_monitoring
    - prometheus
    - grafana

- name: Configurar Servidores Remotos (Node Exporter)
  hosts: remote_servers
  become: yes
  roles:
    - tls_node_exporter
    - nginx_proxy
    - node_exporter