- name: Configure Monitoring Servers
  hosts: monitoring_server
  become: yes
  roles:
    - tls_monitoring
    - prometheus
    - grafana

- name: Configure Remote Servers (Node Exporter)
  hosts: remote_servers
  become: yes
  roles:
    - tls_node_exporter
    - nginx_proxy
    - node_exporter
