- name: Update repositories
  apt:
    update_cache: yes

- name: Install Node Exporter
  apt:
    name: prometheus-node-exporter
    state: present

- name: Enable and restart Node Exporter
  service:
    name: prometheus-node-exporter
    enabled: yes
    state: restarted
