- name: Install Prometheus
  apt:
    name: prometheus
    state: present

- name: Configure Prometheus
  copy:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: Change ownership of certificate files to root:prometheus
  file:
    path: "{{ item }}"
    owner: root
    group: prometheus
    mode: '0644'
  loop:
    - /etc/ssl/certs/monitoring/monitoring.crt
    - /etc/ssl/certs/monitoring/monitoring.key
  notify: Restart Prometheus

- name: Add Prometheus TLS config 
  copy:
    dest: /etc/prometheus/web-config.yml
    content: |
      tls_server_config:
        cert_file: /etc/ssl/certs/monitoring/monitoring.crt
        key_file: /etc/ssl/certs/monitoring/monitoring.key
  notify: Restart Prometheus

- name: Ensure Prometheus systemd service uses TLS config
  lineinfile:
    path: /usr/lib/systemd/system/prometheus.service
    regexp: '^ExecStart='
    line: 'ExecStart=/usr/bin/prometheus --web.config.file=/etc/prometheus/web-config.yml'
  notify: Reload systemd and Restart Prometheus
