- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Upload Nginx configuration for Node Exporter
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/node_exporter

- name: Create a symbolic link for Nginx configuration
  file:
    src: /etc/nginx/sites-available/node_exporter
    dest: /etc/nginx/sites-enabled/node_exporter
    state: link

- name: Restart Nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted
